server:
  verbosity: 1
  interface: 0.0.0.0@5353
  port: 5353
  do-ip4: yes
  do-ip6: yes
  do-udp: yes
  do-tcp: yes
  access-control: 127.0.0.0/8 allow
  access-control: 10.0.0.0/8 allow
  access-control: 172.16.0.0/12 allow
  access-control: 192.168.0.0/16 allow
  access-control: ::1 allow

  hide-identity: yes
  hide-version: yes
  harden-glue: yes
  harden-dnssec-stripped: yes
  use-caps-for-id: yes
  cache-min-ttl: 300
  cache-max-ttl: 86400
  prefetch: yes
  prefetch-key: yes
  qname-minimisation: yes
  aggressive-nsec: yes

  # Privacy: no logging of queries by default
  logfile: ""
  use-syslog: no

  root-hints: "/opt/unbound/etc/unbound/root.hints"
  auto-trust-anchor-file: "/opt/unbound/etc/unbound/root.key"

forward-zone:
  name: "."
  forward-tls-upstream: no
  forward-addr: 1.1.1.1@53
  forward-addr: 1.0.0.1@53
  forward-addr: 8.8.8.8@53
  forward-addr: 8.8.4.4@53
