#!/usr/bin/env bash
set -euo pipefail
SUPPORT="$HOME/Library/Application Support/Rakshak"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
echo "=== Rakshak doctor ==="
echo "1) Processes"
pgrep -lax Rakshak 2>/dev/null || echo "  (no Rakshak GUI)"
pgrep -laf RakshakDaemon 2>/dev/null || echo "  (no RakshakDaemon)"
pgrep -lax coredns 2>/dev/null || echo "  (no coredns)"
echo ""
echo "2) Port 9847 (local API)"
lsof -nP -iTCP:9847 -sTCP:LISTEN 2>/dev/null || echo "  NOT LISTENING — start: $ROOT/run.sh"
echo ""
echo "3) Port 53 (DNS)"
sudo lsof -nP -iUDP:53 -iTCP:53 2>/dev/null | head -5 || echo "  nothing on 53 (DNS not active)"
echo ""
echo "4) API state"
curl -sS --max-time 2 http://127.0.0.1:9847/api/v1/state 2>/dev/null | python3 -m json.tool 2>/dev/null || echo "  API unreachable"
echo ""
echo "5) Last daemon log (20 lines)"
tail -20 "$SUPPORT/Logs/daemon.log" 2>/dev/null || echo "  (no daemon.log)"
echo ""
echo "6) Last CoreDNS log (20 lines)"
tail -20 "$SUPPORT/Logs/coredns.log" 2>/dev/null || echo "  (no coredns.log)"
echo ""
echo "7) Corefile forward line"
grep -E '^[[:space:]]*forward' "$SUPPORT/Corefile" 2>/dev/null || echo "  (no Corefile yet)"
IP="$(ipconfig getifaddr en0 2>/dev/null || true)"
echo ""
echo "8) This Mac LAN IP (en0): ${IP:-unknown}"
if [[ -n "${IP:-}" ]]; then
  echo "9) DNS test (should be 0.0.0.0 for ads):"
  dig @"$IP" doubleclick.net +short +time=2 +tries=1 2>/dev/null || echo "  dig failed"
fi
echo ""
echo "=== Fixes ==="
echo "  Full restart: $ROOT/run.sh"
echo "  Stop all:    pkill -x Rakshak; pkill -f RakshakDaemon; sudo pkill -x coredns"
echo "  Port 53 busy: sudo lsof -nP -iUDP:53 — quit conflicting app or reboot"
